### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by rbozhinov** [xiaomi-sdm660/android_device_xiaomi_clover#1]
<xi:include href="/vendoe/etc/usb_audio_policy_configuration.xml"/>
fix 
<xi:include href="/vendor/etc/usb_audio_policy_configuration.xml"/>

**Comment by rcstar6696** [comment]
What is this ?

**Comment by rbozhinov** [comment]
fix last commit

**Comment by rbozhinov** [comment]
don't "/vendoe

**Comment by rcstar6696** [comment]
Done :)

**Comment by rcstar6696** [comment]
@robzhinov write me at telegram and i will add you to our group 
Max Werfers (rcstar6696)
