### ISSUE TITLE
Successful build does not boot

### ISSUE THREAD

**Issue by stucki** [xiaomi-sdm660/android_device_xiaomi_clover#2]
I am able to build LineageOS 16.0 with these sources using the following manifest:

```
~$ cat .repo/local_manifests/clover.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <!--
  Xiaomi Mi Pad 4 (clover)
  -->
  <project      path="device/xiaomi/clover"             name="xiaomi-sdm660/android_device_xiaomi_clover"               remote="github"         revision="lineage-16.0" />
  <project      path="device/xiaomi/sdm660-common"      name="xiaomi-sdm660/android_device_xiaomi_sdm660-common"        remote="github"         revision="havoc" />
  <project      path="kernel/xiaomi/clover"             name="xiaomi-sdm660/android_kernel_xiaomi_clover"               remote="github"         revision="master" />
  <project      path="vendor/xiaomi/clover"             name="xiaomi-sdm660/android_vendor_xiaomi_clover"               remote="github"         revision="master" />
  <project      path="packages/resources/devicesettings" name="LineageOS/android_packages_resources_devicesettings"     remote="github"         revision="lineage-16.0" />
  <project      path="vendor/xiaomi/MiuiCamera"         name="xiaomi-sdm660/android_vendor_xiaomi_Miuicamera"           remote="github"         revision="master" />
</manifest>
```

I can flash the result in TWRP without errors, but following this, I end up in fastboot all the time.
When trying to boot only `boot.img` via fastboot, I get the following error:

```
~$ fastboot boot boot.img
downloading 'boot.img'...
OKAY [  2.203s]
booting...
FAILED (remote: Failed to load/authenticate boot image: 00000050)
finished. total time: 2.206s
```

Two weeks ago, I was able to successfully build and install LineageOS 16.0 for the Mi Pad 4 using sources from https://github.com/parfrost/android_device_xiaomi_clover. Unfortunately, the author removed the `lineage-16.0` branch so I can't see what has changed. I remember that it used sdm660-common, vendor and kernel from here (https://github.com/xiaomi-sdm660).

When the boot failed, I went back to TWRP and installed the previous image (using device tree from user parfrost) again. This works fine, so I'm now with a working Mi Pad 4, but I cannot update it.

Any idea what's wrong?

**Comment by rcstar6696** [comment]
Your manifest is wrong. We have no lineage-16.0 branch

**Comment by stucki** [comment]
https://github.com/xiaomi-sdm660/android_device_xiaomi_clover/tree/lineage-16.0

**Comment by rcstar6696** [comment]
Use havoc branch for clover and lineageify it

**Comment by rcstar6696** [comment]
Thats not my branch ASK @PythonLimited

**Comment by stucki** [comment]
The two branches are already more or less the same:
https://github.com/xiaomi-sdm660/android_device_xiaomi_clover/compare/havoc...lineage-16.0?expand=1

But sure, looking forward to hear from @PythonLimited. That's why I asked here :-)

**Comment by rcstar6696** [comment]
Try fastboot flash Boot

**Comment by stucki** [comment]
Did this too. Flashing works, but it ends up in a bootloop again (always coming back to the fastboot screen).

**Comment by stucki** [comment]
I will now start a new build using the `los-16.0-new` branch for sdm660-common (instead of `havoc`).

**Comment by rcstar6696** [comment]
this will not work
please try "redo" kernel branch

**Comment by stucki** [comment]
Thanks, will do!

**Comment by stucki** [comment]
@rcstar6696 Just to be sure: `redo` branch for kernel, and what branch for sdm660-common? `los-16.0-new` or `havoc`?

**Comment by rcstar6696** [comment]
havoc

**Comment by stucki** [comment]
Thanks!

**Comment by rcstar6696** [comment]
join our support group on telegram if you want https://t.me/mipad4support

**Comment by stucki** [comment]
With the `redo` kernel branch it boots! However, the screen resolution is much lower than before now. Everything is sized ca. twice as big as before.

Thanks for the link. Do you mind if I create Github issues instead? This would help others to find about known issues.

**Comment by rcstar6696** [comment]
this has nothing to do with the tree now we builded lineage withou any issues for mi pad 4 with redo kernel
i guess you are useing modified trees

**Comment by PythonLimited** [comment]
which branches are u using in the other repos?
I did my build about a week ago, back then i had no problems on my MiPad (64GB LTE).
Maybe something else changed in the trees since then.
Other thing u could try is the using havoc branch instead of the lineage-16.0 - if it still wont boot this isnt related to this repo...

**Comment by stucki** [comment]
@rcstar6696 You were right, I made a mistake. Updated the manifest but did not update sources. So I was still using the `los-16.0-new` branch for sdm660-common :-)

However, after updating and building again, everything has worked as it should!

@PythonLimited Here is my current manifest:
```
~$ cat .repo/local_manifests/clover.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <!--
  Xiaomi Mi Pad 4 (clover)
  -->
  <project      path="device/xiaomi/clover"             name="xiaomi-sdm660/android_device_xiaomi_clover"               remote="github"         revision="lineage-16.0" />
  <project      path="device/xiaomi/sdm660-common"      name="xiaomi-sdm660/android_device_xiaomi_sdm660-common"        remote="github"         revision="havoc" />
  <project      path="kernel/xiaomi/clover"             name="xiaomi-sdm660/android_kernel_xiaomi_clover"               remote="github"         revision="redo" />
  <project      path="vendor/xiaomi/clover"             name="xiaomi-sdm660/android_vendor_xiaomi_clover"               remote="github"         revision="master" />
  <project      path="packages/resources/devicesettings" name="LineageOS/android_packages_resources_devicesettings"     remote="github"         revision="lineage-16.0" />
  <project      path="vendor/xiaomi/MiuiCamera"         name="xiaomi-sdm660/android_vendor_xiaomi_Miuicamera"           remote="github"         revision="master" />
</manifest>
```
This works and the device runs great. Only SElinux is still disabled, but I guess that's a known problem...

Thanks for your work both of you, great job!
