### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by stucki** [xiaomi-sdm660/android_device_xiaomi_clover#4]
Hi all!

I'm following up to #2 where I documented my manifest to build LineageOS 16.0 for clover.

After checking again today, I see that there are now 6 branches in https://github.com/xiaomi-sdm660/android_device_xiaomi_sdm660-common of which 4 were updated in the last 4 days.

So @coderzstas @StyloGey @tytydraco @rcstar6696 can you please point out what your branches are meant for and if they have any dependencies on specific branches in other projects (e.g. kernel)?

I would be happy if this ticket remains open for the time being or if you move this information to a wiki page where such information can be found...

Thanks in advance!

**Comment by rcstar6696** [comment]
Use havoc branch like in the manifest we shared if something New will be used in the builds i will change manifest
There is no plan for a wiki 
The other branchs are not 100% ok for clover

**Comment by stucki** [comment]
Thanks for the super fast feedback!

May I ask @coderzstas to update these two repos then?

- https://github.com/xiaomi-sdm660/android_build_manifest/blob/los-16.0/xiaomi_manifest.xml
- https://github.com/xiaomi-sdm660/android_build_manifest/blob/los-16.0-new/local_manifest.xml

Both branches don't include the havoc branch for sdm660-common.

**Comment by rcstar6696** [comment]
They not even include clover because those are not fully compatible with clover so the los manifest are useless for you

**Comment by stucki** [comment]
You have a point here. However, isn't that exactly what I was asking for? :-)
Having a lineageos-16.0-clover branch in the manifests repo would therefore be a nice thing.

Reason: Because it works pretty great after all! :-)

**Comment by rcstar6696** [comment]
its not there because no one of us maintains  los for clover so we will not add it except one maintainer will be found

**Comment by stucki** [comment]
Hmm ok. I was assuming that @coderzstas is taking care of it since he worked on the two branches...

**Comment by rcstar6696** [comment]
he doesn't own clover only me and @pythonlimited

**Comment by stucki** [comment]
Like I said, he's been doing a great job so far. If he has no plans to continue work on the device, then someone else will hopefully continue from here...

**Comment by PythonLimited** [comment]
@stucki I'm doing those los 16.0 builds from time to time. I use the havoc branches, if u don't feel comfortable with those u could also check out this guys github although I don't know how much it has been updated....
https://github.com/GuaiYiHu/android_device_xiaomi_clover

Regards

**Comment by tytydraco** [comment]
@stucki My branch is the havoc-develop branch. Essentially it's a place where untested / experimental commits go that may eventually be merged into another more stable branch. So far this has never been the case, since my branch is new, and others refuse to believe it exists.

**Comment by stucki** [comment]
@PythonLimited Thanks for the feedback. Build runs very well using the `havoc` branch. So my manifest from https://github.com/xiaomi-sdm660/android_device_xiaomi_clover/issues/2#issuecomment-458726106 is still ok!
Only had a quick look at the other repo you mention. It has not been updated since November. Did not compare, but I don't think it can be much better than what we have. /cc @GuaiYiHu 

@tytydraco Thanks for clarifying!

So is anyone of you planning or interested in making clover an official build for LineageOS? Right now it looks like only SElinux enforcement is missing, correct?

**Comment by PythonLimited** [comment]
why not, it would be great as i dont got the processing power to compile for 3+ devices at a time...
What about we submit one...

**Comment by stucki** [comment]
@PythonLimited Can you pm me please? You can find my email at the Github profile page...
